import numpy as np

In [80]:
import numpy as np
import plotly.graph_objects as go

In [81]:
#y=4.76x1+3.4x2+3.5+eps



In [184]:
x1=np.arange(-10,10,0.1)
x2=np.arange(-5,5,0.05)
x3=np.ones(x1.shape)
X1=np.vstack((x1,x2,x3))
X1=X1.T
X1

array([[-1.00000000e+01, -5.00000000e+00,  1.00000000e+00],
       [-9.90000000e+00, -4.95000000e+00,  1.00000000e+00],
       [-9.80000000e+00, -4.90000000e+00,  1.00000000e+00],
       [-9.70000000e+00, -4.85000000e+00,  1.00000000e+00],
       [-9.60000000e+00, -4.80000000e+00,  1.00000000e+00],
       [-9.50000000e+00, -4.75000000e+00,  1.00000000e+00],
       [-9.40000000e+00, -4.70000000e+00,  1.00000000e+00],
       [-9.30000000e+00, -4.65000000e+00,  1.00000000e+00],
       [-9.20000000e+00, -4.60000000e+00,  1.00000000e+00],
       [-9.10000000e+00, -4.55000000e+00,  1.00000000e+00],
       [-9.00000000e+00, -4.50000000e+00,  1.00000000e+00],
       [-8.90000000e+00, -4.45000000e+00,  1.00000000e+00],
       [-8.80000000e+00, -4.40000000e+00,  1.00000000e+00],
       [-8.70000000e+00, -4.35000000e+00,  1.00000000e+00],
       [-8.60000000e+00, -4.30000000e+00,  1.00000000e+00],
       [-8.50000000e+00, -4.25000000e+00,  1.00000000e+00],
       [-8.40000000e+00, -4.20000000e+00

In [140]:
a=np.array([4.76,3.4,3.5])
y=np.dot(X,a)
y+=np.random.normal(scale=10,size=y.shape)
y.shape

(200,)

In [131]:
fig=go.Figure(data=[go.Scatter3d(x=X[:,0],y=X[:,1],z=y)])
fig.show()

In [179]:
#y=a_1*x_1+a_2*x_2+a_3+eps
L=0.03
eta=np.array([0,0,0])
h=np.dot(X,eta)
e=(h-y)**2
J=0
for i in range(1,200):
    J+=e[i]
J/=2
for i in range (1,200):
    for j in range(0,3):
        eta[j]=eta[j]-L*(h[i]-y[i])*X[i][j]
    print(eta)
eta

[-12  -6   1]
[-14  -7   1]
[-9 -4  0]
[0 0 0]
[-1  0  0]
[2 1 0]
[-19  -9   2]
[-26 -12   2]
[-28 -13   2]
[-16  -7   0]
[-13  -5   0]
[-21  -9   1]
[-34 -15   2]
[-41 -18   2]
[-44 -19   2]
[-51 -22   2]
[-58 -25   2]
[-63 -27   2]
[-73 -32   3]
[-57 -24   1]
[-53 -22   0]
[-44 -17  -1]
[-52 -21   0]
[-54 -22   0]
[-51 -20   0]
[-68 -28   2]
[-67 -27   1]
[-62 -24   0]
[-69 -27   1]
[-65 -25   0]
[-68 -26   0]
[-53 -18  -2]
[-55 -19  -1]
[-55 -19   0]
[-70 -26   2]
[-69 -25   1]
[-64 -22   0]
[-59 -19   0]
[-66 -22   1]
[-58 -18   0]
[-64 -21   1]
[-69 -23   2]
[-73 -25   2]
[-75 -26   2]
[-86 -31   4]
[-91 -33   5]
[-102  -38    7]
[-100  -37    6]
[-95 -34   5]
[-87 -30   3]
[-83 -28   2]
[-86 -29   2]
[-85 -28   1]
[-94 -32   3]
[-97 -33   3]
[-101  -35    4]
[-98 -33   3]
[-95 -31   2]
[-94 -30   1]
[-98 -32   2]
[-103  -34    3]
[-95 -30   1]
[-86 -25  -1]
[-82 -23  -1]
[-86 -25   0]
[-87 -25   0]
[-83 -23   0]
[-85 -24   0]
[-86 -24   0]
[-92 -27   2]
[-88 -25   0]
[-93 -27   1

array([39, 20,  3])

In [182]:
x1=np.random.uniform(-10,10,200)
x2=np.random.uniform(-10,10,200)
x3=np.ones(x1.shape)

X=np.vstack((x1,x2,x3))
X=X.T

a=np.array([4.76,3.4,3.5])
y=np.dot(X,a)
y+=np.random.normal(scale=10,size=y.shape)
#via using gradient decent let's optimise this
X.shape

(200, 3)

In [183]:
#h=a_1*x_1+a_2*x_2+a_3+eps
L=0.01
eta=np.array([0,0,0],dtype=float)
h=np.dot(X,eta)
e=(h-y)**2
J=0
# for i in range(1,200):
#     h=np.dot(X,eta)
#     J+=1/2*(h[i]-y[i])**2
# J is a cost function
n=3000
for i in range(n):
    h=np.dot(X,eta)
    for j in range(0,3):
        t=0
        # for k in range(X.shape[0]):
        #     t+=(h[i]-y[i])*X[k,j]
        # t/=X.shape[0]
        eta[j]=eta[j]-L*(np.dot((h-y),X[:,j])).sum()/X.shape[0]
        # eta[j]=eta[j]-L*t
eta

array([5.08793479, 2.97431076, 3.64268237])

In [172]:
h=np.dot(X,eta)

In [191]:
h=np.dot(X,eta)
h1=np.dot(X1,eta)
fig=go.Figure()
fig.add_trace(go.Scatter3d(x=X[:,0],y=X[:,1],z=h,mode="markers"))
fig.add_trace(go.Scatter3d(x=X1[:,0],y=X1[:,1],z=h1,mode="markers"))

fig.show()